### PR TITLE
add 'http' with resource_url starts with //

### PR DESCRIPTION
**Pull request by alexandre**
Ensure that resource_url starts with 'http'.

### CODE REVIEW

**Comment by mbr** [comment]
The ``//`` is intentional, it will cause the browser to use the protocol that the original request has been made with. The proposed change would actually drop HTTPS if force SSL is not enabled.

**Comment by alexandre** [comment]
And when I'm not using a browser to process it? (e.g. a lib to put the css inline)

**Comment by mbr** [comment]
I would assume you either pass the URL through unchanged or the tool knows how to handle it? It's a widespread practice and `RFC compliant <http://tools.ietf.org/html/rfc3986#section-4.2>`_. Which library are you having issues with?

**Comment by alexandre** [comment]
@mbr ok, with inlinestyler.

**Pull request closed without merging**
