### PR TITLE
Swap from deprecated flask.ext.* to flask_*

### PR DESCRIPTION
**Pull request by jeffwidman**
For background details, see: https://github.com/pallets/flask/commit/d3d8a4694a9c1601e213d6b5f27fab34615609b7

### CODE REVIEW

**Comment by jeffwidman** [comment]
Ping @mbr

**Comment by jeffwidman** [comment]
Bump

**Comment by mbr** [comment]
Merged. Sorry, missed this for a while. =)

**Comment by jeffwidman** [comment]
Weird, what happened to the commit? Not showing up for me in project commit history...

**Comment by mbr** [comment]
Well, it seems that you submitted this approximately 10 Month ago. A month later, I seem to have (I don't recall) updated the docs and such independently (see `git blame`).

I rebased your commit, but since the changes were already incorporated, it essentially became a NOOP, I think.

**Comment by jeffwidman** [comment]
Oh that makes sense. Thanks.

**Pull request merged**
