### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by lihuii**
Fix three typos in docs.

### CODE REVIEW

**Comment by mbr** [comment]
Thank you, merged!

**Comment by lihuii** [comment]
You are welcome. By the way, I just completed the chinese translation of the docs ([here](http://flask-bootstrap-zh.readthedocs.io/zh/latest/)), can you add a link in `readme.md` or docs?

**Comment by mbr** [comment]
You could add the link yourself and make a pull request, if that is not too
much to ask. You'll have to find a good fit, I'll admit, I wasn't prepared
for someone translating the docs! =)

**Comment by greyli** [comment]
All right. Let me try.

2016-10-26 2:16 GMT+08:00 Marc Brinkmann <notifications@github.com>:

> You could add the link yourself and make a pull request, if that is not too
> much to ask. You'll have to find a good fit, I'll admit, I wasn't prepared
> for someone translating the docs! =)
>

**Pull request merged**
