### PR TITLE
Enable the User-ID feature in google analytics

### PR DESCRIPTION
**Pull request by tejovanthn**
Copied the ```uanalytics``` macro to support Tracking Info -> User-ID feature in google analytics.
screenshot from 2015-03-24 20 32 19

### CODE REVIEW

**Comment by mbr** [comment]
I didn't know about the analytics user id feature. It sounds horrifying =).

Regardless, adding another macro is not the way to go, it is better to extend the existing one for such a simple change. ``ga()`` works the same way.

**Comment by mbr** [comment]
I believe your example might be nonfunctional. I haven't used Google Analytics in a long time, so take what I say with a grain of salt. However, ``&uid`` and ``userId`` are just two ways of setting the UserID on the tracker (according to https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference). Regardless of how you do it, I think it's necessary to do that before sending the page view.

729234e should enable what you want (also note that the ``domain`` argument seems obsolete now). Here's an example:

```jinja
{{google.uanalytics('U-XX-YYYY', {'userId': 'myUser'})}}
```

Results in the following code being generated:

```js
  ga('create', "U-XX-YYYY", {"userId": "myUser"});
  ga('send', 'pageview');
```

This should (hopefully) do what you want (see https://developers.google.com/analytics/devguides/collection/analyticsjs/user-id). I will update the docs.

**Comment by mbr** [comment]
Docs are updated in 4c65994. That should do it.

**Comment by tejovanthn** [comment]
Ahh! Thanks :)

**Pull request closed without merging**
